# @license BSD-3 https://opensource.org/licenses/BSD-3-Clause
# Copyright (c) 2024, Institute of Automatic Control - RWTH Aachen University
# Maximilian Nitsch (m.nitsch@irt.rwth-aachen.de)
# All rights reserved.

# This custom ROS 2 action file defines the calibration for the KELLER Series 10LHPX. 
# See https://keller-druck.com/en/products/pressure-transmitters/oem-high-pressure-transmitters/series-10lhpx for more information.

# Request
uint16 calibration_duration
---
# Result
float64 calibrated_pressure
---
# Feedback
float64 average_pressure